--------------------------------------------------------
--  DDL for Table TARIFF
--------------------------------------------------------

  CREATE TABLE "HR"."TARIFF" 
   (	"PLAN_ID" NUMBER, 
	"PLAN_NAME" VARCHAR2(30 BYTE), 
	"PLAN_ACTIVE" VARCHAR2(20 BYTE), 
	"PLAN_ACT_DEACT_DATE" TIMESTAMP (6), 
	"PLAN_ACTIVATION_FEE" NUMBER, 
	"SECURITY_DEPOSIT" NUMBER, 
	"MONTHLY_RENTAL" NUMBER, 
	"FREE_LOCAL" NUMBER, 
	"FREE_STD" NUMBER, 
	"FREE_SMS" NUMBER, 
	"OUT_LOCAL_NETWORK" NUMBER, 
	"OUT_LOCAL_OUT_NETWORK" NUMBER, 
	"OUT_LOCAL_OUT_LANDLINE" NUMBER, 
	"OUT_STD" NUMBER, 
	"OUT_ISD" NUMBER, 
	"OUT_ROAMING_LOCAL" NUMBER, 
	"OUT_ROAMING_STD" NUMBER, 
	"IN_NORMAL" NUMBER, 
	"IN_ROAMING" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TARIFF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TARIFF_PK" ON "HR"."TARIFF" ("PLAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TARIFF
--------------------------------------------------------

  ALTER TABLE "HR"."TARIFF" ADD CONSTRAINT "TARIFF_PK" PRIMARY KEY ("PLAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HR"."TARIFF" MODIFY ("PLAN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  DDL for Trigger TARIFF_PLAN_ID_TRIGGER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HR"."TARIFF_PLAN_ID_TRIGGER" 
   before insert on "HR"."TARIFF" 
   for each row 
begin  
   if inserting then 
      if :NEW."PLAN_ID" is null then 
         select TARIFF_SEQ.nextval into :NEW."PLAN_ID" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "HR"."TARIFF_PLAN_ID_TRIGGER" ENABLE;


--------------------------------------------------------
--  DDL for Table TARIFF_PLAN_NAME
--------------------------------------------------------

  CREATE TABLE "HR"."TARIFF_PLAN_NAME" 
   (	"PLAN_NAME" VARCHAR2(30 BYTE), 
	"PLAN_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TARIFF_PLAN_NAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."TARIFF_PLAN_NAME_PK" ON "HR"."TARIFF_PLAN_NAME" ("PLAN_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TARIFF_PLAN_NAME
--------------------------------------------------------

  ALTER TABLE "HR"."TARIFF_PLAN_NAME" ADD CONSTRAINT "TARIFF_PLAN_NAME_PK" PRIMARY KEY ("PLAN_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HR"."TARIFF_PLAN_NAME" MODIFY ("PLAN_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TARIFF_PLAN_NAME
--------------------------------------------------------

  ALTER TABLE "HR"."TARIFF_PLAN_NAME" ADD CONSTRAINT "TARIFF_PLAN_NAME_FK" FOREIGN KEY ("PLAN_ID")
	  REFERENCES "HR"."TARIFF" ("PLAN_ID") ENABLE;

--------------------------------------------------------
--  DDL for Sequence TARIFF_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HR"."TARIFF_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1020 CACHE 20 NOORDER  NOCYCLE ;
