--------------------------------------------------------
--  File created - Saturday-October-29-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TARIFF_PLAN_NAME
--------------------------------------------------------

  CREATE TABLE "VIVEK"."TARIFF_PLAN_NAME" 
   (	"PLAN_NAME" VARCHAR2(30 BYTE), 
	"PLAN_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TARIFF_PLAN_NAME_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VIVEK"."TARIFF_PLAN_NAME_PK" ON "VIVEK"."TARIFF_PLAN_NAME" ("PLAN_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TARIFF_PLAN_NAME
--------------------------------------------------------

  ALTER TABLE "VIVEK"."TARIFF_PLAN_NAME" ADD CONSTRAINT "TARIFF_PLAN_NAME_PK" PRIMARY KEY ("PLAN_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TARIFF_PLAN_NAME
--------------------------------------------------------

  ALTER TABLE "VIVEK"."TARIFF_PLAN_NAME" ADD CONSTRAINT "TARIFF_PLAN_NAME_FK" FOREIGN KEY ("PLAN_ID")
	  REFERENCES "VIVEK"."TARIFF" ("PLAN_ID") ENABLE;
